=== mansuk2022/mansuk2022/Gift card xml/catalog_20048454.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CardStore">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Store">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Logo" />
              <xs:element name="Name" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="GiftCards">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="GiftCard">
                <xs:complexType>
                  <xs:sequence>
                    <xs:choice maxOccurs="unbounded">
                      <xs:element name="cards" type="xs:string" />
                      <xs:element name="CardID" type="xs:string" />
                      <xs:element name="type" type="xs:string" />
                      <xs:element name="Validity">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="ExpDate" type="xs:string" />
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="Discount">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="DiscountType" type="xs:string" />
                            <xs:element name="Discription" type="xs:string" />
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="AcceptedStore">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="StoreName">
                              <xs:complexType>
                                <xs:sequence>
                                  <xs:element maxOccurs="unbounded" name="name1" type="xs:string" />
                                </xs:sequence>
                              </xs:complexType>
                            </xs:element>
                            <xs:element name="Address">
                              <xs:complexType>
                                <xs:sequence>
                                  <xs:element maxOccurs="unbounded" name="address1" type="xs:string" />
                                </xs:sequence>
                              </xs:complexType>
                            </xs:element>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="Cost" type="xs:string" />
                      <xs:element name="UserNumber" type="xs:string" />
                    </xs:choice>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ShopDetails">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Address">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="City" type="xs:string" />
                    <xs:element name="ZipCode" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Contact">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Mobile" type="xs:string" />
                    <xs:element name="Email" type="xs:string" />
                    <xs:element name="LandLine" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Webpage" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mansuk2022/mansuk2022/Gift card xml/catalog_20048454.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type ="text/css" href="catalog_20048454.css"?>
<?xml-model href="catalog_20048454.dtd" type="application/xml-dtd"?>
<CardStore 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="catalog_20048454.xsd">
        <Store id="header">
                <Logo></Logo>
                <Name> London Store </Name>
        </Store>
        <GiftCards>
                <GiftCard>
                        <cards> Eleo-Card </cards>
                        <CardID>Card ID: 101 </CardID>
                        <type>Type: Can purchase Electronic Item </type>
                        <Validity>
                                <ExpDate>Exp Date: 2023-Dec-10th </ExpDate>
                        </Validity>
                        <Discount>
                                <DiscountType>Discount:  Huge Discount </DiscountType>
                                <Discription>Discription: This Discount can cover upto 90% of actual price </Discription>
                        </Discount>
                        <AcceptedStore>
                                <StoreName>
                                        <name1> Ox Store </name1>
                                        <name1>  Food Store  </name1>
                                        <name1> Countyr-Side Store </name1>
                                </StoreName>
                                <Address >
                                        <address1>=> London, Oxford Stret </address1>
                                        <address1>=> London,Royal Street </address1>
                                        <address1>=> London, Queen Street </address1>
                                </Address>
                        </AcceptedStore>
                        <Cost>Cost: £15 </Cost>
                        <UserNumber>UserName: 1 </UserNumber>
                </GiftCard>
                <GiftCard>
                        <cards> Fodo-Card </cards>
                        <type> Can purchase Food Item </type>
                        <CardID> 102 </CardID>
                        <Validity>
                                <ExpDate> 2023-Apr-13rd </ExpDate>
                        </Validity>
                        <Discount>
                                <DiscountType> Medium  Discount </DiscountType>
                                <Discription> This Discount can cover upto 50% of actual price </Discription>
                        </Discount>
                        <AcceptedStore>
                                <StoreName>
                                        <name1> Ox Store </name1>
                                        <name1>  Food Store  </name1>
                                        <name1> Countyr-Side Store </name1>
                                </StoreName>
                                <Address>
                                        <address1> London, Oxford Stret </address1>
                                        <address1> London,Royal Street </address1>
                                        <address1> London, Queen Street </address1>
                                </Address>
                        </AcceptedStore>
                        <Cost> £10 </Cost>
                        <UserNumber> 1 </UserNumber>
                </GiftCard>
                <GiftCard>
                        <cards> DGame-Card </cards>
                        <type>  Can purchase Digital Game Item </type>
                        <CardID> 103 </CardID>
                        <Validity>
                                <ExpDate> 2023-Oct-01st </ExpDate>
                        </Validity>
                        <Discount>
                                <DiscountType> Medium Discount </DiscountType>
                                <Discription> This Discount can cover upto 15% of actual price </Discription>
                        </Discount>
                        <AcceptedStore>
                                <StoreName>
                                        <name1> Ox Store </name1>
                                        <name1>  Food Store  </name1>
                                        <name1> Countyr-Side Store </name1>
                                </StoreName>
                                <Address>
                                        <address1> London, Oxford Stret </address1>
                                        <address1> London,Royal Street </address1>
                                        <address1> London, Queen Street </address1>
                                </Address>
                        </AcceptedStore>
                        <Cost> £5 </Cost>
                        <UserNumber> 3 </UserNumber>
                </GiftCard>
        </GiftCards>
        <ShopDetails id="footer">
                <Address>
                        <City>City: London: Oxford Street </City>
                        <ZipCode>ZipCode: 123 </ZipCode>
                </Address>
                <Contact>
                        <Mobile>Mobile Number: +1231351335 </Mobile>
                        <Email>Email: LondonStore@gmail.com </Email>
                        <LandLine>Landline: 020-1241112 </LandLine>
                </Contact>
                <Webpage>Webpage: https://LondonStore.com </Webpage>
        </ShopDetails>

</CardStore>
